#pragma once

#define VIAL_KEYBOARD_UID {0x29, 0xD1, 0x43, 0xC7, 0x4C, 0x55, 0xF6, 0x90}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 14 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define VIAL_ENCODER_DEFAULT { RGB_VAD, RGB_VAI, KC_VOLD, KC_VOLU, C(KC_Z), C(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }
